
†

John Smithjsmith@example.net"
724-8557-966"
122-2812-498*+
Main StreetPodunkBongo Bongo Land «ø2€«ÈÞ:ºB
Ó
Jane Publicjane@allyourbasearebelongto.us"
613-5435-600"
622-9015-145"
973-3670-856*(
Main StreetAnytownWaikikamukau ‡–*+
Heywood CedarsAnytownWaikikamukau á”2À£›Ï:Ë	B
(
x
Jock Tamsonskynet555@example.org"
223-8330-609*'
Heywood CedarsAnytownTimbuktu Û˜2ÀÚÉÃ:È
B	
‚
Susie Macksyoga@macks.com"
835-5702-733"
134-7464-173*&
Heywood CedarsPodunkTimbuktu ¤‡2àÇ°×:ÅB

